/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinalmotos;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Interfaz2 extends javax.swing.JFrame {

    
    
    Moto obj=new Moto();
    
       DefaultTableModel modelo;
      
    public Interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalmotos/diseno-logotipo-motorista-coche-dibujado-mano_23-2149936367.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 210));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Registrar Nueva Motocicleta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 260, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 438, 240));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Motos Disponibles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Clientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 430, 250));

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Vender Motocicleta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 260, 50));

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton5.setText("Ver Total Ventas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 260, 50));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 210, 240));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Motos Vendidas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton7.setText("Actualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, 30));

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton6.setText("Motocicleta mas Cara");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 260, 50));

        jButton8.setBackground(new java.awt.Color(153, 204, 255));
        jButton8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton8.setText("Motocicleta mas Barata");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 260, 50));

        jButton9.setBackground(new java.awt.Color(153, 204, 255));
        jButton9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 260, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalmotos/images.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 190, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalmotos/fondo.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 1190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        ///Capturamos los datos
        
        String Vin=JOptionPane.showInputDialog("Ingrese el VIN de la Moto");
        String Marca=JOptionPane.showInputDialog("Ingrese la MARCA de la moto");
        String Linea=JOptionPane.showInputDialog("Ingrese la LINEA de la moto");
        int Cilindraje=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el CILINDRAJE de la moto"));
        int Modelo=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el MODELO de la moto"));
        String FechaIngreso = JOptionPane.showInputDialog("Ingrese la fecha de ingreso  (Formato: dd/MM/yyyy):" + Linea);
        float Precio=Float.parseFloat(JOptionPane.showInputDialog("Ingrese el precio"));
        
        
        
      
        ////validamos que las fechas ingresadas esten en el formato correcto

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;
        try {
            date = dateFormat.parse(FechaIngreso);
            
        } catch (ParseException e) {
            // Manejar errores de análisis de fecha
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto. Por favor, ingrese la fecha en el formato dd/MM/yyyy.", "Error", JOptionPane.ERROR_MESSAGE);

        }
        ////creamos un nuevo objeto de la clase mOTO
        
        /// y Le pasamos los valores a los metodos set de los atributos de la clase producto

        Moto Mot=new Moto();
       
        Mot.setVin(Vin);
        Mot.setMarca(Marca);
        Mot.setModelo(Modelo);
        Mot.setLinea(Linea);
        Mot.setPrecio(Precio);
        Mot.setFechaingreso(FechaIngreso);
        Mot.setCilindraje(Cilindraje);
        


///Ejecutamos el metodo que hace el guardado 

  JOptionPane.showMessageDialog(null,obj.RegistrarProducto(Mot));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
      
       String Vin=JOptionPane.showInputDialog("Ingrese el VIN de la Motocicleta que desea Vender");
       String Cliente=JOptionPane.showInputDialog("Ingrese el Nombre del cliente al  que desea Vender");
     ///Ejecutamos el metodo que hace el guardado 

  JOptionPane.showMessageDialog(null, obj.VenderMoto(Vin,Cliente));
          
          
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        
         JOptionPane.showMessageDialog(null,obj.TotalVentas());
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
         modelo = new DefaultTableModel();
        jTable1.setModel(modelo);
        modelo.addColumn("VIN");
        modelo.addColumn("Marca");
        modelo.addColumn("Linea");
        modelo.addColumn("Cilindraje");
        modelo.addColumn("Modelo");
         modelo.addColumn("Fecha Ingreso");
         modelo.addColumn("Precio");
        
        //mostrarmos los datos en la tabla
       
        for (int i = 0; i < obj.Motos.size(); i++) {
        Object[] object = new Object[7];
       
            object[0] = obj.Motos.get(i).getVin();
            object[1] = obj.Motos.get(i).getMarca();
            object[2] = obj.Motos.get(i).getLinea();
            object[3] = obj.Motos.get(i).getCilindraje();
            object[4] = obj.Motos.get(i).getModelo();
            object[5] = obj.Motos.get(i).getFechaingreso();
            object[6] = obj.Motos.get(i).getPrecio();
           
        
        modelo.addRow(object);
        }
        
        
         modelo = new DefaultTableModel();
        jTable2.setModel(modelo);
        modelo.addColumn("VIN");
        modelo.addColumn("Marca");
        modelo.addColumn("Linea");
        modelo.addColumn("Cilindraje");
        modelo.addColumn("Modelo");
         modelo.addColumn("Cliente");
         modelo.addColumn("Precio");
        
        //mostrarmos los datos en la tabla
       
        for (int i = 0; i < obj.MotosVendidas.size(); i++) {
        Object[] object = new Object[7];
       
            object[0] = obj.MotosVendidas.get(i).getVin();
            object[1] = obj.MotosVendidas.get(i).getMarca();
            object[2] = obj.MotosVendidas.get(i).getLinea();
            object[3] = obj.MotosVendidas.get(i).getCilindraje();
            object[4] = obj.MotosVendidas.get(i).getModelo();
            object[5] = obj.MotosVendidas.get(i).getCliente();
            object[6] = obj.MotosVendidas.get(i).getPrecio();
           
        
        modelo.addRow(object);
        }
        
        
        
        
         modelo = new DefaultTableModel();
        jTable3.setModel(modelo);
        modelo.addColumn("Cliente");
        
        //mostrarmos los datos en la tabla
       
        for (int i = 0; i < obj.Clientes.size(); i++) {
        Object[] object = new Object[1];
       
            object[0] = obj.Clientes.get(i);
           
           
        
        modelo.addRow(object);
        }
        
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        
        
         JOptionPane.showMessageDialog(null,""+obj.MayorPrecio());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

 JOptionPane.showMessageDialog(null,""+obj.MenorPrecio());

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      
        
        JOptionPane.showMessageDialog(null, "ADIOS!!");
        
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
